# Generated by Django 3.1.2 on 2020-11-10 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObsNmsko1H',
            fields=[
                ('obs_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('ta_2m', models.FloatField(blank=True, null=True)),
                ('pa_avg', models.FloatField(blank=True, null=True)),
                ('rh_avg', models.FloatField(blank=True, null=True)),
                ('ws_avg', models.FloatField(blank=True, null=True)),
                ('wd_avg', models.FloatField(blank=True, null=True)),
                ('ws_max', models.FloatField(blank=True, null=True)),
                ('wd_ws_max', models.FloatField(blank=True, null=True)),
                ('pr_sum', models.FloatField(blank=True, null=True)),
                ('hg', models.FloatField(blank=True, db_column='HG', null=True)),
                ('pm10', models.FloatField(blank=True, db_column='PM10', null=True)),
                ('pm2_5', models.FloatField(blank=True, db_column='PM2_5', null=True)),
                ('so2', models.FloatField(blank=True, db_column='SO2', null=True)),
                ('no', models.FloatField(blank=True, db_column='NO', null=True)),
                ('no2', models.FloatField(blank=True, db_column='NO2', null=True)),
                ('nox', models.FloatField(blank=True, db_column='NOx', null=True)),
                ('co', models.FloatField(blank=True, db_column='CO', null=True)),
                ('ben', models.FloatField(blank=True, db_column='BEN', null=True)),
                ('h2s', models.FloatField(blank=True, db_column='H2S', null=True)),
                ('o3', models.FloatField(blank=True, db_column='O3', null=True)),
            ],
            options={
                'db_table': 'obs_nmsko_1h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Si',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.SmallIntegerField()),
                ('ii', models.BigIntegerField()),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('cccc', models.CharField(blank=True, max_length=4, null=True)),
                ('cc', models.CharField(blank=True, max_length=2, null=True)),
                ('iso_cc', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('elev', models.FloatField(blank=True, null=True)),
                ('info', models.CharField(blank=True, max_length=32, null=True)),
                ('vtime', models.DateTimeField()),
                ('mtime', models.DateTimeField()),
                ('changed_id', models.IntegerField(blank=True, null=True)),
                ('changes', models.CharField(blank=True, max_length=32, null=True)),
                ('ue', models.BooleanField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'si',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('si_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='airMonitor.si')),
            ],
            options={
                'db_table': 'si',
                'managed': False,
            },
            bases=('airMonitor.si',),
        ),
    ]
