# Generated by Django 3.1.2 on 2020-11-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airMonitor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station',
        ),
    ]
