# Generated by Django 3.1.3 on 2020-12-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airMonitor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station',
        ),
    ]
